// <auto-generated />
using KAYITt.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KAYITt.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220911125319_InitlaCreate")]
    partial class InitlaCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KAYITt.Models.student", b =>
                {
                    b.Property<int>("öğrenciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("öğrenciId"), 1L, 1);

                    b.Property<string>("AD")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SOYAD")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("İLÇE")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ŞEHİR")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("öğrenciId");

                    b.ToTable("students");
                });
#pragma warning restore 612, 618
        }
    }
}
